### PR TITLE
i18n: syntax and semantic correction fr

### PR DESCRIPTION
**Pull request by VanSlanzar**
I missed a huge syntax and semantic problem on 2 lines. I checked everything again because I don't want to make requests all time to you. 

Sorry for the inconvenience.

### CODE REVIEW

**Comment by Baertram** [comment]
No problem, translations are always a bit troubling. Especially as you need to test them ingame for the correct "length" at the UI elements etc. (or at least you should do that :-p )

**Comment by VanSlanzar** [comment]
I do, but the interface reloads are a bit of a pain ^^. Could you tell me if the "option that hides linked objects in the bank deposit tab" works for you. Because I have the impression that for me not. Or maybe I didn't quite understand this option.
Example: (the sithis axe) that is linked to my character always appears in the bank deposit tab whether the option is activated or not.

**Comment by Baertram** [comment]
You should disable all other addons to make the interface reload quick, it will only take a few seconds then.
/reloadui into chat, return key, done within 3 seconds (depends on your CPU and server load).

Which option do you refer to, could you name me the constant/translated value from the translation please?

**Comment by VanSlanzar** [comment]
L.219    lamHideCharBoundAtBankDeposit = "Hide char bound items at bank",
L.220    lamHideCharBoundAtBankDepositTT = "Hide character bound items at the bank deposit tab",

This should hide a linked item (weapon, item, consumable)? 
I have already try a weapon and consumable. It doesn't work for me.

**Comment by Baertram** [comment]
It's no filter so your items are not hidden/shown by this setting! 
It only affects the AdvancedFilters added subfilter buttons enabled/disabled state at the bank deposit tab, and will change this state if the item is character bound.
You can see it belongs to the subfilter buttons as the headline at the settings is telling you.

Showing/Hiding items is not controlled via AF settings, but via the subfilter buttons and/or the dropdown filters.

**Comment by VanSlanzar** [comment]
I think my problem comes from the fact that in French we have a lot of synonyms.
The first option: disables the buttons of the subcategories
the second: what it hide? (buttons, elements or objects ) of category or (object in the game)?

I'm back ^^.

**Comment by VanSlanzar** [comment]
will this also update the translation on minion?

**Comment by Baertram** [comment]
Minion is providing the same zip file as manually downloaded from www.esoui.com, so: yes
But I need to update it first which might take some time as current PTS version for High Isle is in scope and might need changes.

**Comment by VanSlanzar** [comment]
Alright, thanks for the info.

**Pull request merged**
